name: S3 file upload from Github repository
on:
  push:
    branches:
      - main
job:
  upload-to-s3:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: AKIA22CTUXLJYLUUEY4N
          aws-secret-access-key: 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
          aws-region: us-east-1

      - name: Upload files to S3
        run: |
          aws s3 cp . s3://githubaction-sott-demo/ --recursive
